### ISSUE TITLE
Reconnect websocket connection when getting "WebSocket is already in CLOSING or CLOSED state."

### ISSUE THREAD

**Issue by wolkenarchitekt** [hbenl/mpc-js-web#1]
I'm connecting to MPD via websockets (using websockify), which works fine. Like this (code simplified):
```
import {MPC} from "mpc-js-web";

// initialize MPC at beginning
const websocketUri = `ws://${window.location.hostname}:${window.location.port}/websockify`;
mpc = new MPC();
mpc.connectWebSocket(websocketUri);

// playing (event handler)
mpc.currentPlaylist.clear();
mpc.currentPlaylist.add(file);
mpc.playback.play();
```

Problem is, once the websocket connection closes (seems there is some timeout in my case), I will get errors on subsequent play events:
```
socketWrapper.js:45 WebSocket is already in CLOSING or CLOSED state.
```

Once that happens, I couldn't find a way how to reconnect mpc-js to MPD. Calling `mpc.connectWebsocket` again fails, neither does it help to call `mpc.connection.close` before reconnecting. 

Is there a way to manually or automatically re-establish the websocket connection once it's in CLOSING/CLOSED state?

**Comment by hbenl** [comment]
Have you tried calling `mpc.disconnect()` before calling `mpc.connectWebSocket()` again?

**Comment by wolkenarchitekt** [comment]
Calling `mpc.disconnect()` and then reconnecting before every command seems to help, no CLOSE errors anymore.
